
export const SET_LOADING = "SET_LOADING";

export const SET_VERIFICATION_CODE = "SET_VERIFICATION_CODE";
export const SET_EMAIL_FOR_RESET_PASSWORD = "SET_EMAIL_FOR_RESET_PASSWORD";

export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const VALIDATE_TOKEN_ATTEMPT = "VALIDATE_TOKEN_ATTEMPT";
export const VALIDATE_TOKEN_FAILED = "VALIDATE_TOKEN_FAILED";
export const VALIDATE_TOKEN_SUCCESS = "VALIDATE_TOKEN_SUCCESS";

export const LOGOUT_ATTEMPT = "LOGOUT_ATTEMPT";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_ATTEMPT = "REGISTER_ATTEMPT";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const UPDATE_USER_ATTEMPT = "UPDATE_USER_ATTEMPT";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const SEND_VERIFICATION_CODE = "SEND_VERIFICATION_CODE";
export const RESEND_VERIFICATION_CODE = "RESEND_VERIFICATION_CODE";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const VERIFY_EMAIL_ATTEMPT = "VERIFY_EMAIL_ATTEMPT";
export const VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";



export const SET_PRE_QUIZ = "SET_PRE_QUIZ";

export const UPDATE_QUIZ_ATTEMPT = "UPDATE_QUIZ_ATTEMPT";
export const UPDATE_QUIZ_FAILED = "UPDATE_QUIZ_FAILED";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";

export const UPDATE_ASSESSMENT_ATTEMPT = "UPDATE_ASSESSMENT_ATTEMPT";
export const UPDATE_ASSESSMENT_FAILED = "UPDATE_ASSESSMENT_FAILED";
export const UPDATE_ASSESSMENT_SUCCESS = "UPDATE_ASSESSMENT_SUCCESS";

export const UPDATE_MEMBERSHIP_ATTEMPT = "UPDATE_MEMBERSHIP_ATTEMPT";
export const UPDATE_MEMBERSHIP_FAILED = "UPDATE_MEMBERSHIP_FAILED";
export const UPDATE_MEMBERSHIP_SUCCESS = "UPDATE_MEMBERSHIP_SUCCESS";
